# Training configuration
n_epoch: 10
gradient_accumulation_step: 2
precision_type: "no"
project_name: "diffulab"
use_ema: true
ema_update_after_step: 0
ema_update_every: 10
log_validation_images: true
val_steps: 50
compile: true
