# CIFAR10 dataset configuration
train:
  _target_: diffulab.datasets.ImageNetLatentREPA
  data_path: "data/imagenet"
  local: true
  batch_size: 256
  split: "train"

val:
  _target_: diffulab.datasets.ImageNetLatentREPA
  data_path: "data/imagenet"
  local: true
  batch_size: 256
  split: "val"
