# configs/train_cifar10_flow_matching.yaml
# @package _global_
defaults:
  - model: dit
  - diffuser: rectified_flow
  - trainer: default
  - dataset: cifar10
  - dataloader: default
  - optimizer: adamw
  - _self_

# Override specific settings
trainer:
  project_name: cifar10_flow_matching
  n_epoch: 100

diffuser:
  n_steps: 100

dataloader:
  batch_size: 32

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
