name: Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/unit_tests.yml'
      - 'tests/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  if: github.event.pull_request.draft == false
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            sources:
              - src/**
              - tests/**
              - .github/workflows/unit_tests.yml

      - name: Install uv
        if: steps.changes.outputs.sources == 'true'
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: "Set up Python"
        if: steps.changes.outputs.sources == 'true'
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        if: steps.changes.outputs.sources == 'true'
        run: uv sync --all-extras

      - name: Run tests
        if: steps.changes.outputs.sources == 'true'
        run: uv run pytest --junitxml=results.xml

      - name: Upload test report
        if: steps.changes.outputs.sources == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml
